# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexwithimagepage',
            name='show_placeholder',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animallitterpedigreelink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree_link', to='core.AnimalLitterPage', unique=True),
        ),
    ]
