# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaldetailpage',
            old_name='colouring',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='juvenile',
            old_name='colouring',
            new_name='colour',
        ),
        migrations.AlterField(
            model_name='animaldetailpage',
            name='sex',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='juvenile',
            name='birth_weight',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='juvenile',
            name='sex',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=255),
        ),
    ]
