# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170304_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleIndexPage',
            fields=[
                ('articleindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticleIndexPage')),
                ('news_list_style', models.CharField(choices=[(b'title_intro_link', b'Articles with title and intro with link.'), (b'full_no_link', b'Full articles with no link.')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.articleindexpage',),
        ),
        migrations.CreateModel(
            name='NewsArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ArticlePage')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.articlepage',),
        ),
    ]
